### ISSUE TITLE
product enable disable option require

### ISSUE THREAD

**Issue by jamil2342** [jamil2342/eservice#35]
There should be option for to enable and disable product. disable product should not be shown at client portal.

**Comment by tanvir-csedu** [comment]
This is done. Please check

**Comment by jamil2342** [comment]
please make it simple. just give a check box. if user check this than it will be enable when deselect this it will be disable. just for enable or disable this pressing too manu button is wrong. place the checkbox at the leftmost column before product name

**Comment by tanvir-csedu** [comment]
It's unnecessary. I follow standard. Everywhere use this format. So it's not required
