### ISSUE TITLE
the product allignment is not right 

### ISSUE THREAD

**Issue by jamil2342** [jamil2342/eservice#40]
![capture](https://cloud.githubusercontent.com/assets/18321259/16361174/a6bfab2c-3ba8-11e6-9d4a-fdff907ba42d.PNG)

see this picture for setting up mind

**Comment by tanvir-csedu** [comment]
This is done. Please check

**Comment by jamil2342** [comment]
this is not done yet see this image from this url

http://192.169.175.239/test/Client/index.jsp?categoryId=28
![capture](https://cloud.githubusercontent.com/assets/18321259/16712741/2861c93a-46b2-11e6-83c1-f27c68759928.PNG)
