### ISSUE TITLE
remove save button from cart page

### ISSUE THREAD

**Issue by jamil2342** [jamil2342/eservice#42]
remove the save button from the cart page. while changing the value from numeric updown the price should be automatically updated. you can follow the chaldal.com or meenabazar.com

**Comment by tanvir-csedu** [comment]
Vai,
First of all, why we do only copy paste ?? I am not following "chaldal.com or meenabazar.com"

I told in the first meeting that I follow "amazon/ flipcart/ daraz". So that I think this post is fully unnecessary.
