### ISSUE TITLE
add shipping cost while shopping

### ISSUE THREAD

**Issue by jamil2342** [jamil2342/eservice#44]
Here http://192.169.175.239/test/Client/viewcart.jsp only product price is included. but the shipping cost 25 taka should be added also. this 25 taka should be configurable by admin portal.

**Comment by tanvir-csedu** [comment]
![1](https://cloud.githubusercontent.com/assets/18412690/16725700/457a4efc-477a-11e6-8034-ef30bbecb6b4.PNG)
![2](https://cloud.githubusercontent.com/assets/18412690/16725701/45cfe68c-477a-11e6-885f-7067eaf4dd68.PNG)
