### ISSUE TITLE
the filter and sort is not properly allign with the menu   

### ISSUE THREAD

**Issue by jamil2342** [jamil2342/eservice#45]
http://192.169.175.239/test/Client/index.jsp?categoryId=28 
at this url see this issue

![capture](https://cloud.githubusercontent.com/assets/18321259/16712809/1e8b3228-46b4-11e6-8264-b60606672e8b.PNG)

**Comment by jamil2342** [comment]
![capture](https://cloud.githubusercontent.com/assets/18321259/16726684/58e9fa3c-477f-11e6-8043-c7d125d4e968.PNG)

**Comment by tanvir-csedu** [comment]
My PC has not that kinds of resolution, So that I can't notice that issue. Now check please
